security:
    firewalls:
        login_firewall:
            pattern:    /login$
            anonymous:  ~
        secured_area:
            pattern:    ^/
            anonymous: false
            form_login:
                login_path:  webaccess_bugtracker_login
                check_path:  webaccess_bugtracker_login_check
                default_target_path: webaccess_bugtracker_dashboard
            logout:
                path:   /logout
                target: /login
            remember_me:
                key: %secret%
                lifetime: 3600
                path: /
                domain: ~
    access_control:
        - { path: user.*, role: ROLE_ADMIN }
        - { path: company.*, role: ROLE_ADMIN }
        - { path: project.*, role: ROLE_ADMIN }

    providers:
        main:
            entity: { class: WebaccessBugtrackerBundle:User, property: username }

    encoders:
        Webaccess\BugtrackerBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
