parameters:
#    webaccess_bugtracker.example.class: Webaccess\BugtrackerBundle\Example

services:
#    webaccess_bugtracker.example:
#        class: %webaccess_bugtracker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
